### ISSUE TITLE
Submit a post

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#1]
As a **site user** I can **post to the site** so that **I can share my interests/views**

### Acceptance Criteria

- [x] Users can post items to the board
- [x] Posted content shows up on the board

### Tasks

- [x] Create post form
- [x] Wire up post form
