### ISSUE TITLE
Upload a profile picture

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#10]
As a **site user** I can **upload a profile picture** so that **I can **

### Acceptance Criteria

- [x] Users can upload profile pictures
- [x] Profile pictures can be seen next to the username

### Tasks

- [x] Add picture upload feature
- [x] Display pictures next to usernames
