### ISSUE TITLE
Like a post/comment

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#11]
As a **site user** I can **click like on posts** so that **I can show support for quality posts**

### Acceptance Criteria

- [x] Users can like other users' posts
- [x] Likes can then be seen on the posts

### Tasks

- [x] Create liking functionality
- [x] Display likes where relevant
