### ISSUE TITLE
See own posts

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#12]
As a **site user** I can **see my own posts and comments on my profile page** so that **I can keep track of my posts**

### Acceptance Criteria

- [x] User posts can be seen on the profile page
- [x] User comments can be seen on the profile page

### Tasks

- [x] Create functions for retrieving the user's content from the database
- [x] Add buttons for viewing the content on the profile page
