### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#14]
As a **site user** I can **view profile pages** so that **I can interact better with other users**

### Acceptance Criteria

- [x] Each user has a profile page
- [x] Profile pages can be accessed by clicking a user

### Tasks

- [x] Create profile page template
- [x] Create profile page view
- [x] Link to profile page from username
