### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#15]
As a **site user** I can **register an account** so that **I can post to the site**

### Acceptance Criteria

- [x] Users can register an account
- [x] Registered users can log in and post content

### Tasks

- [x] Create account registration
- [x] Create log-in / log-out functions
