### ISSUE TITLE
Search the forum

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#16]
As a **site user** I can **search the forum** so that **I can find existing topics**

### Acceptance Criteria

- [x] The home page should have a search bar
- [x] Searching should return a list of relevant posts

### Tasks

- [x] Create search function
- [x] Add search bar to home page
