### ISSUE TITLE
Edit/delete own posts

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#2]
As a **site user** I can **edit or delete my posts** so that **I can change my mind**

### Acceptance Criteria

- [x] Users can edit their own posts
- [x] Users can delete their own posts

### Tasks

- [x] Add post editing features
- [x] Add post deletion functionality
- [x] Add edit/delete buttons under posts
