### ISSUE TITLE
Register an account

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#3]
As a **site user** I can **register an account** so that **I can become a member of the site**

### Acceptance Criteria

- [x] Users can register accounts
- [x] Registered users can log in
- [x] Being logged in enables posting

### Tasks

- [x] Create account registration
- [x] Add sign-in/register content
- [x] Enable posting and editing for registered users
