### ISSUE TITLE
Moderate content

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#5]
As a **Site admin** I can **edit and delete user posts** so that **I can deal with spam and abusive or illicit content**

### Acceptance Criteria

- [x] The admin panel has tools for managing user posts
- [x] Admins can edit and delete user posts

### Tasks

- [x] Create editing/deleting capabilities
- [x] Add them to the admin page
