### ISSUE TITLE
Comment on a post

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#7]
As a **site user** I can **comment on posts** so that **I can communicate with other users**

### Acceptance Criteria

- [x] Users can add comments to posts
- [x] Comments appear in threads

### Tasks

- [x] Create comment form
- [x] Make comments appear on the post's page
