### ISSUE TITLE
View list of threads

### ISSUE THREAD

**Issue by EmilionR** [EmilionR/django-pp4#8]
As a **site user** I can **view a list of  post threads** so that **I can find current and previous topics easily**

### Acceptance Criteria

- [x] Given more than one post in the database, posts appear in a list
- [x] When a user opens the main page, a list of posts is seen

### Tasks

- [x] Create post list view
